services:
  warp-proxy:
    image: ghcr.io/kingcc/warproxy:latest
    restart: always
    volumes:
      - ./data/warp-proxy:/config
    environment:
      - WARP_PLUS=false
      - HTTP_PORT=1081
      - TZ=Asia/Tokyo
      - VERBOSE=true
    ports:
      - "1081:1081"
    profiles:
      - warp-proxy
    networks:
      - internal_network
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1081 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
  proxy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - proxy
    volumes:
      - ./.config/Caddyfile:/etc/caddy/Caddyfile
      - ./.config/certificate.pem:/etc/ssl/certs/certificate.pem
      - ./.config/key.pem:/etc/ssl/private/key.pem
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    networks:
      - internal_network

  app:
    image: ghcr.io/lqvp/misskey-tempura:latest
    restart: always
    environment:
      COREPACK_INTEGRITY_KEYS: 0
    links:
      - db
      - keydb
    depends_on:
      db:
        condition: service_healthy
      keydb:
        condition: service_healthy
      warp-proxy:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - internal_network
    volumes:
      - ./.config/default.yml:/misskey/.config/default.yml:ro

  keydb:
    restart: always
    image: eqalpha/keydb:alpine
    networks:
      - internal_network
    volumes:
      - ./data/keydb:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: groonga/pgroonga:latest-debian-16
    ports:
      - '5430:5432'
    networks:
      internal_network:
      misskey-postgres:
          ipv4_address: 10.0.0.2
    env_file:
      - .config/.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run
    profiles:
      - tunnel
    env_file:
      - .config/.env
    networks:
      - internal_network


networks:
  internal_network:
  misskey-postgres:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/27

volumes:
  mi-backups:
