doco_cd_age_key: ENC[AES256_GCM,data:o9WcMc8WHvR4+LxnYQ6f89XGuABt8f73KZml8zkp2vzkcvfNZh5SJYaIU8fX1oN6tgzeps0XY93RXZ+jmk+SYBMEu2Zh3Es221p+g9cQBZWEG4IvGpZeLgmVnRrrxsnpwtKLEF+IUROKCV2n2Q4z05C90NzygCF1nPgNfmmqpfwVnVbm3f7zt970xx2EHz2FIScuFRfROrfwsiaVDRj9MCFZkORNZf8H2jaMQzpPrqiVeINmD45OEEtZZMdM,iv:DOoTg6bC03DtM9DPAZ/yWI38wYN711kDeIZu2MrGkoM=,tag:IYiv6HdpARXCtdrgfRurfA==,type:str]
apprise_notify_urls: ENC[AES256_GCM,data:nsdrjMz5WpLIj6/YRiuhukYx0+7TbXNunQnc6vde8ipbGGOyecaZrZ1VqBR0xNdesQo/YhxpDHlHl4lb+4rsGvruQFzW3iNYzoXe6nb3IlmTBmHPYDdcmEZKFlzV6mR+oo1Y,iv:gqahoY+9zo1bT3fzaf98CnuWZHCLWE1yu9xHUaHdazY=,tag:VJ8+bjZdVZyxnLUxxFW/PA==,type:str]
admin_user_password_hash: ENC[AES256_GCM,data:WKCtjGfbmZZmeRo5Fy/4zzOpP4lG1XZrmbFMXpPM1ER3+ikIEjbALHjILERULYwdifOmTYztQ5FD5ijoltYRgx4lJoiOB5R8KvKIof2KSRO731GsnnQak7aUjRVgTmvfXsFin5ZrsVFDXPC8zq6cfYxb2V6/+BW0,iv:HsdUnCUTCMq3uFh+5x69ZT0Z0CJ9+1Nnz4DC0iXRgx4=,tag:JwOJ76W3BSuhtLgF0V3jNA==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:0ku/GoqljbpbmZVSkT/tHaQnqLngrhvS8Gek3bFqVFr39Uryi7aUSA7TwFSWSVLKtoDA2sPjBo0ntVHKUg==,iv:mKORLINf4yGHSHlSw/9lYmmHTPxfDPDCvMEwaBzP+20=,tag:Qkmo/SeyUw9pn3fVuy33nA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOHdnKzR4RStVdVoycW1r
            K1RZVnR4REZOUUNkT3hNWmR5QWl2M0pUUlQwCnpGc3ZpRUxLcXoyUWZXekxkeE1P
            c3poK3hSbjFjdkkwWU90UTBuWjhOancKLS0tIG9DN2VXbS9xQjVNVGY2UUM3ejNV
            bFVGQnRmcGtJQjFZU2dLNlUySkE5S28KTp7GuFf148Zw4TqeA44lC/XLBSBucu9w
            TYshd1tXKDFWpLsm2+Ztn9ieMPwbC1/SdPW2uR0kdTPHbNY7iAiPUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145yagqxlptxtw0jg3yawdqj6r6075l3svdakhhe6t7u4nfterg7qall256
    lastmodified: "2026-09-09T17:03:08Z"
    mac: ENC[AES256_GCM,data:SrI/2dXR4NXhAeXIRk4wjHEpvQrDiOaF9ctWI9yB3/Nzj58coxzfX/Pzt+yz0V0Cobp3HhRo9KFok0hdgKl0+XkFsaeEydATmdRBjkCPPaqqJbEaMDfEH4l0zcO7rPeRc8zz7ts6azhLeMo3+Nk+l6BhEdSiC83WQ6SpBIEj/w0=,iv:TAUY8aug7qJlEQ9ZcY/rOO6f0d8MzRswP67rlBJh8DM=,tag:ffqemNHzzZThtGMpnMr9KA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
