name: Update submodules
on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-24.04
    env:
      TZ: "Asia/Tokyo"
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -am "Automatically update submodules"
        if git diff --cached --quiet; then
          echo "No changes detected."
        else
          git commit -m 'update: sorted domains.txt'
          git push origin main
        fi
      
