name: Update submodules
on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-24.04
    env:
      TZ: "Asia/Tokyo"
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Update submodules
      run: |
        git config --global protocol.file.allow always
        git submodule init
        git submodule update
        git submodule foreach git pull origin main
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m "Automatically update submodules"
        git push origin main
      
